### ISSUE TITLE
Issues subscribing to specific podcast

### ISSUE THREAD

**Issue by EricBrunel** [stonega/tsacdop#25] opened 2020-10-02 19:06 UTC
I tried to subscribe to the 'First Action Bureau' podcast. It seems to work, but no episodes are shown, and trying to refresh it displays 'Update failed; network error'. But my network is working fine, and I could subscribe to other podcasts with no issue.
This podcast can be found by searching 'First Action Bureau' in Tsacdop, or by entering the URL:
https://feeds.captivate.fm/first-action-bureau/

**Comment by stonega** [comment] 2020-10-03 08:59
Thanks for bug report, the reason of the issue is error happened when parse pub date in the rss feed.
I have fixed it in latest commit.

**Comment by EricBrunel** [comment] 2020-10-03 20:06
Awesome, thank you!

**Comment by stonega** [comment] 2020-10-14 17:39
I have fixed the issue in v0.5.0. Please let me know if it works for you after update.

**Comment by EricBrunel** [comment] 2020-10-14 18:41
I updated, and it works now. Closing the issue. Thank you!

**Comment by Oymate** [comment] 2021-01-09 07:44
Another issue on this, I seem to not be able to subscribe to this one
https://cast.postmarketos.org/feed.rss

**Comment by stonega** [comment] 2021-01-09 08:51
@Oymate  Thanks for the report, I will have a check.

**Comment by stonega** [comment] 2021-01-09 10:58
@Oymate The issue has beed fixed in v0.5.4, pleae let me know it work for you after update.

**Closed** 2021-01-13 05:10 UTC

**Comment by Oymate** [comment] 2021-01-14 11:15
Works :)
